
export const studentData = [
    {
        id: 1,
        name: "John Doe",
        email: "Abc@gmail.com",
        phone: "+91-1234567890",  
        course: "Microsoft Excel Core",
        batch_id: "101-101-001",
        status: "Active",
        type: "Student",
        registrationDate: "2023-01-15",
        lastLogin: "2023-10-01",
        progress: 75,
        notes: "Needs improvement in JavaScript",
        profilePicture: "https://example.com/profile1.jpg",
    },
    {
        id: 2,
        name: "GVM College",
        email: "",
        phone: "",  
        course: "powerBI Core",
        type:"Educational Institute",
        batch_id: "102-101-002",
        status: "Active",
        registrationDate: "2023-02-20",
        lastLogin: "2023-10-02",
        progress: 85,
        notes: "Excellent performance in Python",
        profilePicture: "https://example.com/profile2.jpg",
    },
    {
        id: 3,
        name: "Alice Johnson",
        email: "",
        phone: "",  
        course: "Machine Learning",
        batch_id: "101-101-001",
        status: "Inactive",
        registrationDate: "2023-03-10",
        lastLogin: "2023-09-25",
        progress: 60,
        notes: "Struggling with algorithms",
        profilePicture: "https://example.com/profile3.jpg",
    },
    {
        id: 4,
        name: "Bob Brown",
        email: "",
        phone: "",  
        course: "Cyber Security",
        batch_id: "101-101-001",
        status: "Active",
        registrationDate: "2023-04-05",
        lastLogin: "2023-10-03",
        progress: 90,
        notes: "Great understanding of network security",
        profilePicture: "https://example.com/profile4.jpg",
    },
    {
        id: 5,
        name: "Charlie Green",
        email: "",
        phone: "",  
        course: "Cloud Computing",
        batch_id: "101-101-001",
        status: "Active",
        registrationDate: "2023-05-15",
        lastLogin: "2023-10-04",
        progress: 80,
        notes: "Needs to work on AWS concepts",
        profilePicture: "https://example.com/profile5.jpg",
    },
]